### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by the-solipsist** [RoliSoft/LetsEncrypt-CloudFlare-Hook#2]
This is a great script.  Much easier to understand that the python hook for Cloudflare and letsencrypt.sh.  So thank you!

How do you run deploy.sh in such a manner that the certs for example.org can be placed in `/etc/ssl/private/example.org/` with ownership being `root:ssl-cert` and the permissions for the `example.org` directory being `755` (world-readable/executable) and the permissions of file that `privkey.pem` links to being `640` and the permissions of the files that `cert.pem`, `chain.pem`, and `fullchain.pem` link to being `644`.  (All the symbolic links themselves should be `777`.)

Would you do this by shifting $BASEDIR or by executing mv commands in deploy.sh?  If the latter, how would you make it run with sudo privileges so as to move files to `/etc/ssl/`?

Here is a good link on permissions: https://github.com/letsencrypt/letsencrypt/issues/1473#issuecomment-175785058

**Comment by RoliSoft** [comment]
I run the whole letsencrypt.sh script as root, so the deploy.sh script can also mv, chmod and whatnot freely.

That being said, it's probably not recommended to do so due to security concerns.

One other option would be setting the owner of deploy.sh to root and then setting the `suid` bit, however most unices don't allow this, so you could perhaps work around this by writing a Go app to deploy the certificates, and then set the `suid` bit on its compiled binary.

However, the more correct solution would probably be to play around with the `sudoers` file to allow password-less access to the deploy script. Just make sure the script you write does not allow root escalation by accident.

You could also come up with a concoction where letsencrypt.sh is run as a regular user, then deploy.sh makes note of the new files, and a secondary cron job running as root would fix permissions.

**Comment by the-solipsist** [comment]
@RoliSoft: Thanks for that detailed response!

> However, the more correct solution would probably be to play around with the sudoers file to allow password-less access to the deploy script. 

This I can do.

> Just make sure the script you write does not allow root escalation by accident.

What would the script look like / what precisely should I avoid?
